# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 805bb68535580790198cd8b25e337cb0bf8917f82aed8597e6bf37b1d468448a9b60bb559ad4af45a015640dd476c1da6e5f6598d8a0c03c19c4ee0ebb65f666

test:
  secret_key_base: 502f6efbdeb7cafbcf4cc53906ee4340428809d3f87f0268f392b19394fefc20b1e60b46c3e8ba9f633575a6b458167dd6fd67f2c09b8d9e8d96d027cf794e01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
